=== mashakereb/ProgrammingTechnologies/Lab4/xml/Gems.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        targetNamespace="GemNS"
        xmlns="GemNS"
        elementFormDefault="qualified">

    <xs:element name="Gem">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="gems">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="gem" type="Gem" maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="name">
        <xs:restriction base="xs:string" />
    </xs:simpleType>

    <xs:simpleType name="value">
        <xs:restriction base="xs:float" />
    </xs:simpleType>

    <xs:simpleType name="facesNumber">
        <xs:restriction base="xs:positiveInteger" />
    </xs:simpleType>

    <xs:simpleType name="color">
        <xs:restriction base="xs:string" />
    </xs:simpleType>

    <xs:simpleType name="transparency">
        <xs:restriction base="xs:nonNegativeInteger" />
    </xs:simpleType>

    <xs:simpleType name="preciousness" >
        <xs:restriction base="xs:string">
            <xs:enumeration value="precious" />
            <xs:enumeration value="semiprecious" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="origin">
        <xs:restriction base="xs:string" />
    </xs:simpleType>

    <xs:complexType name="Gem">
        <xs:sequence>
            <xs:element name="Name" type="name"></xs:element>
            <xs:element name="Value" type="value"></xs:element>
            <xs:element name="Origin" type="origin"></xs:element>
            <xs:element name="Preciousness" type="preciousness"></xs:element>

            <xs:element name="VisualParameters">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Color" type="color"></xs:element>
                        <xs:element name="Transparency" type="transparency"></xs:element>
                        <xs:element name="FacesNumber" type="facesNumber"></xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>

</xs:schema>

=== mashakereb/ProgrammingTechnologies/Lab4/xml/gems2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><Gem xmlns="GemNS" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="GemNS Gems.xsd">
    <gems>
        <gem id="g1">
            <Name>Emerald</Name>
            <Value>0.61</Value>
            <Origin>Columbia</Origin>
            <Preciousness>precious</Preciousness>
            <VisualParameters>
                <Color>green</Color>
                <Transparency>50</Transparency>
                <FacesNumber>18</FacesNumber>
            </VisualParameters>
        </gem>
        <gem id="g2">
            <Name>Garnet</Name>
            <Value>0.52</Value>
            <Origin>Tanzania</Origin>
            <Preciousness>precious</Preciousness>
            <VisualParameters>
                <Color>Red</Color>
                <Transparency>20</Transparency>
                <FacesNumber>30</FacesNumber>
            </VisualParameters>
        </gem>
        <gem id="g3">
            <Name>Tourmaline</Name>
            <Value>1.29</Value>
            <Origin>Brasilia</Origin>
            <Preciousness>precious</Preciousness>
            <VisualParameters>
                <Color>pink</Color>
                <Transparency>60</Transparency>
                <FacesNumber>50</FacesNumber>
            </VisualParameters>
        </gem>
        <gem id="g4">
            <Name>Jasper</Name>
            <Value>36</Value>
            <Origin>Madagascar</Origin>
            <Preciousness>semiprecious</Preciousness>
            <VisualParameters>
                <Color>brown</Color>
                <Transparency>0</Transparency>
                <FacesNumber>8</FacesNumber>
            </VisualParameters>
        </gem>
        <gem id="tss">
            <Name>Gagg</Name>
            <Value>1.2</Value>
            <Origin>Ukraine</Origin>
            <Preciousness>precious</Preciousness>
            <VisualParameters>
                <Color>red</Color>
                <Transparency>12</Transparency>
                <FacesNumber>15</FacesNumber>
            </VisualParameters>
        </gem>

    <gem id="pon"><Name>Diamond</Name><Value>500</Value><Origin>Nigeria</Origin><Preciousness>precious</Preciousness><VisualParameters><Color>White</Color><Transparency>100</Transparency><FacesNumber>150</FacesNumber></VisualParameters></gem></gems>
</Gem>
